
[credentials]
usernames = { 
  carolina = { name = "Carolina Rocha", email = "carolina@exemplo.com", password = "$2b$12$KX..." },
  admin    = { name = "Admin", email = "admin@exemplo.com", password = "$2b$12$AB..." }
}

[cookie]
name = "meu_app_cookie"
key = "uma_chave_secreta_aleatoria"
expiry_days = 7

[preauthorized]
emails = ["carolina@exemplo.com"]
